apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-api-ingress
  labels:
    app: {{.Values.name}}
    user-http01-solver: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  rules:
  - host: {{.Values.api.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.name}}-svc-api
          servicePort: {{.Values.api.containerPort}}
  tls:
    - hosts:
      - {{.Values.api.host}}
      secretName: {{.Values.name}}-api-ingress-cert
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-ui-ingress
  labels:
    app: {{.Values.name}}
    user-http01-solver: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{.Values.ui.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.name}}-svc-ui
          servicePort: {{.Values.ui.containerPort}}
  tls:
    - hosts:
      - {{.Values.ui.host}}
      secretName: {{.Values.name}}-ui-ingress-cert
