{{ $apiContainerPort := $.Values.api.containerPort }}
{{ $uiContainerPort := $.Values.ui.containerPort }}
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-api
  labels:
    app: {{.Values.name}}
    tier: api
spec:
  ports:
    - port: {{$apiContainerPort}}
      protocol: TCP
      targetPort: {{$apiContainerPort}}
  selector:
    app: {{.Values.name}}
    tier: api
  type: ClusterIP
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-ui
  labels:
    app: {{.Values.name}}
    tier: ui
spec:
  ports:
    - port: {{$uiContainerPort}}
      protocol: TCP
      targetPort: {{$uiContainerPort}}
  selector:
    app: {{.Values.name}}
    tier: ui
  type: ClusterIP

