# Generated by Django 2.2.11 on 2020-03-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='board_position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile', to='game.BoardPosition'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='order',
            field=models.FloatField(default=0.879251395004169),
        ),
        migrations.AlterField(
            model_name='tile',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='game.Player'),
        ),
    ]
