# Generated by Django 2.2.11 on 2020-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200315_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='order',
            field=models.FloatField(default=0.3757105759317386),
        ),
        migrations.AlterUniqueTogether(
            name='boardposition',
            unique_together={('x', 'y')},
        ),
    ]
