# Generated by Django 2.2.11 on 2020-03-17 18:25

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200315_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='order',
            field=models.FloatField(default=game.models.default_order),
        ),
        migrations.AlterUniqueTogether(
            name='boardposition',
            unique_together={('x', 'y', 'game')},
        ),
    ]
