# Generated by Django 2.2.11 on 2020-03-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200317_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_turn', to='game.Player'),
        ),
    ]
